TRAINING_DATA = [
    # ---------------- BILLING & FINANCE ----------------
    # Original
    ("I was charged twice for my subscription this month.", "Billing"),
    ("Please refund the unauthorized transaction on my credit card.", "Billing"),
    ("Where can I download my latest payment invoice?", "Billing"),
    ("My payment failed but the amount was deducted from my bank.", "Billing"),
    (
        "Why is my monthly bill higher than what was stated on the pricing page?",
        "Billing",
    ),
    ("I need to update the credit card on file for my auto-renewal.", "Billing"),
    ("Can I get a receipt for the software purchase I made yesterday?", "Billing"),
    ("The promo code I applied at checkout did not reduce the final price.", "Billing"),
    ("I canceled my account last week but still got billed.", "Billing"),
    ("Is there a way to switch from a monthly to an annual billing cycle?", "Billing"),
    ("My wire transfer went through, but my account still says unpaid.", "Billing"),
    ("I am requesting a partial refund for the days the service was down.", "Billing"),
    ("Are there any hidden fees associated with the premium plan upgrade?", "Billing"),
    ("The currency conversion on my statement seems incorrect.", "Billing"),
    ("Please delete my payment details from your database immediately.", "Billing"),
    ("wrong receipt", "Billing"),
    ("my receipt has the wrong amount", "Billing"),
    ("incorrect invoice", "Billing"),
    ("billing error on my receipt", "Billing"),
    ("send the right tax receipt", "Billing"),
    ("why did you charge me twice", "Billing"),
    ("refund my money plz", "Billing"),
    ("cancel my sub and refund", "Billing"),
    ("what is this weird charge on my credit card", "Billing"),
    ("i want to dispute a transaction", "Billing"),
    ("where do I enter my tax ID for the invoice?", "Billing"),
    ("update billing address", "Billing"),
    ("auto renew charged me way too much", "Billing"),
    ("i paid but it still says unpaid", "Billing"),
    ("how much does the enterprise plan cost?", "Billing"),
    ("can I pay with paypal instead?", "Billing"),
    ("discount code didn't work at checkout", "Billing"),
    ("charged for canceled account", "Billing"),
    ("receipt is blank", "Billing"),
    ("need invoice for accounting department", "Billing"),
    # ---------------- TECHNICAL SUPPORT ----------------
    # Original
    (
        "The application crashes every time I click the export to PDF button.",
        "Technical",
    ),
    ("Getting a 500 internal server error on the main dashboard.", "Technical"),
    (
        "The database connection times out after the recent software update.",
        "Technical",
    ),
    ("API responses are returning null values for user profiles.", "Technical"),
    ("Whenever I try to upload a photo, the app freezes completely.", "Technical"),
    (
        "The new patch broke the syncing feature between my phone and laptop.",
        "Technical",
    ),
    (
        "I keep getting a 'syntax error' when trying to run the setup script.",
        "Technical",
    ),
    ("The website is loading incredibly slowly on Google Chrome.", "Technical"),
    ("My data isn't saving when I hit the submit button on the form.", "Technical"),
    ("Are the servers down? I can't connect to the multiplayer lobby.", "Technical"),
    ("The audio is completely out of sync with the video playback.", "Technical"),
    (
        "Memory usage spikes to 100% when I leave the program running in the background.",
        "Technical",
    ),
    ("I am unable to install the application on Windows 11.", "Technical"),
    ("The software keeps throwing a fatal exception code 0x80004005.", "Technical"),
    ("Push notifications are not appearing on my iOS device.", "Technical"),
    ("app crashed", "Technical"),
    ("screen goes black", "Technical"),
    ("getting a 404 error", "Technical"),
    ("software keeps freezing", "Technical"),
    ("submit button doesnt work", "Technical"),
    ("UI is glitching out on mobile", "Technical"),
    ("wont load on my macbook", "Technical"),
    ("why is the system so slow today", "Technical"),
    ("i cant upload my pdf file", "Technical"),
    ("data is missing from the dashboard", "Technical"),
    ("integration with slack failed", "Technical"),
    ("the api is returning a timeout", "Technical"),
    ("my export failed midway", "Technical"),
    ("video won't play", "Technical"),
    ("getting an exception out of bounds error", "Technical"),
    ("the new update broke my workflow", "Technical"),
    ("how do I clear the cache to fix the bug", "Technical"),
    ("app drains my phone battery", "Technical"),
    ("the font is corrupted", "Technical"),
    ("server offline", "Technical"),
    # ---------------- ACCOUNT ACCESS ----------------
    ("I forgot my password and the reset link is not arriving in my inbox.", "Account"),
    ("Unable to log in due to two-factor authentication (2FA) failure.", "Account"),
    ("Please update the primary email address linked to my account.", "Account"),
    (
        "My account has been temporarily locked out after too many login attempts.",
        "Account",
    ),
    (
        "I think my account was hacked, there are logins from another country.",
        "Account",
    ),
    ("How do I permanently delete my profile and all associated data?", "Account"),
    ("I need to transfer admin ownership of this workspace to a colleague.", "Account"),
    ("The system says my username is already taken, but it is my name.", "Account"),
    ("I am not receiving the OTP SMS to verify my mobile number.", "Account"),
    ("Can you merge my two accounts? I accidentally created a duplicate.", "Account"),
    (
        "My profile picture won't update no matter how many times I upload it.",
        "Account",
    ),
    ("I want to opt-out of marketing emails but keep my account active.", "Account"),
    ("My account is marked as suspended, what did I do wrong?", "Account"),
    (
        "I lost my backup codes for the authenticator app, please help me get back in.",
        "Account",
    ),
    (
        "Why can't I access the beta features? My account should have permission.",
        "Account",
    ),
    ("lost password", "Account"),
    ("cant login", "Account"),
    ("locked out", "Account"),
    ("change my email", "Account"),
    ("reset link expired", "Account"),
    ("didn't get the sms code", "Account"),
    ("hacked account", "Account"),
    ("someone logged in from russia", "Account"),
    ("delete my profile", "Account"),
    ("how do i change my username", "Account"),
    ("two factor auth is broken", "Account"),
    ("i lost my phone and need to bypass 2fa", "Account"),
    ("make my coworker an admin", "Account"),
    ("why is my account banned", "Account"),
    ("reactivate my suspended account", "Account"),
    ("session expired keeps popping up", "Account"),
    ("invalid credentials error", "Account"),
    ("my avatar picture is upside down", "Account"),
    ("unsubscribe me from the newsletter", "Account"),
    ("transfer ownership to another email", "Account"),
    # ---------------- HARDWARE & LOGISTICS ----------------
    ("The replacement power adapter has not arrived yet.", "Logistics"),
    ("The package was delivered damaged with broken parts inside.", "Logistics"),
    ("Tracking status shows delivered but I haven't received the parcel.", "Logistics"),
    (
        "I need to return the defective unit under the manufacturer warranty.",
        "Logistics",
    ),
    (
        "My order is missing the HDMI cable that was supposed to be in the box.",
        "Logistics",
    ),
    ("Can I change the shipping address? It hasn't dispatched yet.", "Logistics"),
    ("The courier left the package in the rain and the device is ruined.", "Logistics"),
    ("How long does standard international shipping usually take?", "Logistics"),
    ("I was sent the wrong color, I ordered black but received silver.", "Logistics"),
    ("Please provide a prepaid return shipping label for my RMA request.", "Logistics"),
    (
        "My tracking number says 'Invalid or not found' on the FedEx website.",
        "Logistics",
    ),
    ("Are there any customs duties I need to pay for this shipment?", "Logistics"),
    ("The battery on this device won't hold a charge out of the box.", "Logistics"),
    ("I want to cancel my physical order before it leaves the warehouse.", "Logistics"),
    ("Do you offer expedited overnight shipping? I need this urgently.", "Logistics"),
    ("where is my box", "Logistics"),
    ("tracking says delivered but it's not here", "Logistics"),
    ("wrong item delivered", "Logistics"),
    ("i got the wrong color", "Logistics"),
    ("missing parts in the box", "Logistics"),
    ("arrived broken", "Logistics"),
    ("the screen is cracked from shipping", "Logistics"),
    ("how do i return this physical item", "Logistics"),
    ("send a return label", "Logistics"),
    ("change shipping address", "Logistics"),
    ("express delivery is late", "Logistics"),
    ("fedex lost my package", "Logistics"),
    ("customs held my shipment", "Logistics"),
    ("the device won't turn on out of the box", "Logistics"),
    ("my hardware is defective", "Logistics"),
    ("RMA request for broken machine", "Logistics"),
    ("package was stolen from porch", "Logistics"),
    ("can I pick it up at the warehouse", "Logistics"),
    ("the cable is frayed", "Logistics"),
    ("received the wrong size", "Logistics"),
]
